[package]
name = "connect-axum-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
proc-macro-error = { version = "1.0.4", default-features = false }
quote.workspace = true
syn.workspace = true
